// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryRepository creates a new instance of MockQueryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryRepository {
	mock := &MockQueryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryRepository is an autogenerated mock type for the QueryRepository type
type MockQueryRepository struct {
	mock.Mock
}

type MockQueryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryRepository) EXPECT() *MockQueryRepository_Expecter {
	return &MockQueryRepository_Expecter{mock: &_m.Mock}
}

// ExecuteQuery provides a mock function for the type MockQueryRepository
func (_mock *MockQueryRepository) ExecuteQuery(ctx context.Context, query domain.Query, args ...domain.QueryArgs) (*domain.QueryResponse, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 *domain.QueryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Query, ...domain.QueryArgs) (*domain.QueryResponse, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Query, ...domain.QueryArgs) *domain.QueryResponse); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QueryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Query, ...domain.QueryArgs) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryRepository_ExecuteQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteQuery'
type MockQueryRepository_ExecuteQuery_Call struct {
	*mock.Call
}

// ExecuteQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.Query
//   - args ...domain.QueryArgs
func (_e *MockQueryRepository_Expecter) ExecuteQuery(ctx interface{}, query interface{}, args ...interface{}) *MockQueryRepository_ExecuteQuery_Call {
	return &MockQueryRepository_ExecuteQuery_Call{Call: _e.mock.On("ExecuteQuery",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockQueryRepository_ExecuteQuery_Call) Run(run func(ctx context.Context, query domain.Query, args ...domain.QueryArgs)) *MockQueryRepository_ExecuteQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Query
		if args[1] != nil {
			arg1 = args[1].(domain.Query)
		}
		var arg2 []domain.QueryArgs
		var variadicArgs []domain.QueryArgs
		if len(args) > 2 {
			variadicArgs = args[2].([]domain.QueryArgs)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueryRepository_ExecuteQuery_Call) Return(queryResponse *domain.QueryResponse, err error) *MockQueryRepository_ExecuteQuery_Call {
	_c.Call.Return(queryResponse, err)
	return _c
}

func (_c *MockQueryRepository_ExecuteQuery_Call) RunAndReturn(run func(ctx context.Context, query domain.Query, args ...domain.QueryArgs) (*domain.QueryResponse, error)) *MockQueryRepository_ExecuteQuery_Call {
	_c.Call.Return(run)
	return _c
}
