// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryArgs creates a new instance of MockQueryArgs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryArgs(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryArgs {
	mock := &MockQueryArgs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryArgs is an autogenerated mock type for the QueryArgs type
type MockQueryArgs struct {
	mock.Mock
}

type MockQueryArgs_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryArgs) EXPECT() *MockQueryArgs_Expecter {
	return &MockQueryArgs_Expecter{mock: &_m.Mock}
}
