// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockUnitOfWork_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Commit() *MockUnitOfWork_Commit_Call {
	return &MockUnitOfWork_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockUnitOfWork_Commit_Call) Run(run func()) *MockUnitOfWork_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) Return(err error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) RunAndReturn(run func() error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Membership provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Membership() domain.MembershipRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Membership")
	}

	var r0 domain.MembershipRepository
	if returnFunc, ok := ret.Get(0).(func() domain.MembershipRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.MembershipRepository)
		}
	}
	return r0
}

// MockUnitOfWork_Membership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Membership'
type MockUnitOfWork_Membership_Call struct {
	*mock.Call
}

// Membership is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Membership() *MockUnitOfWork_Membership_Call {
	return &MockUnitOfWork_Membership_Call{Call: _e.mock.On("Membership")}
}

func (_c *MockUnitOfWork_Membership_Call) Run(run func()) *MockUnitOfWork_Membership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Membership_Call) Return(membershipRepository domain.MembershipRepository) *MockUnitOfWork_Membership_Call {
	_c.Call.Return(membershipRepository)
	return _c
}

func (_c *MockUnitOfWork_Membership_Call) RunAndReturn(run func() domain.MembershipRepository) *MockUnitOfWork_Membership_Call {
	_c.Call.Return(run)
	return _c
}

// Organization provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Organization() domain.OrganizationRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Organization")
	}

	var r0 domain.OrganizationRepository
	if returnFunc, ok := ret.Get(0).(func() domain.OrganizationRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.OrganizationRepository)
		}
	}
	return r0
}

// MockUnitOfWork_Organization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Organization'
type MockUnitOfWork_Organization_Call struct {
	*mock.Call
}

// Organization is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Organization() *MockUnitOfWork_Organization_Call {
	return &MockUnitOfWork_Organization_Call{Call: _e.mock.On("Organization")}
}

func (_c *MockUnitOfWork_Organization_Call) Run(run func()) *MockUnitOfWork_Organization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Organization_Call) Return(organizationRepository domain.OrganizationRepository) *MockUnitOfWork_Organization_Call {
	_c.Call.Return(organizationRepository)
	return _c
}

func (_c *MockUnitOfWork_Organization_Call) RunAndReturn(run func() domain.OrganizationRepository) *MockUnitOfWork_Organization_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Rollback() *MockUnitOfWork_Rollback_Call {
	return &MockUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockUnitOfWork_Rollback_Call) Run(run func()) *MockUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) Return(err error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) RunAndReturn(run func() error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) User() domain.UserRepository {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 domain.UserRepository
	if returnFunc, ok := ret.Get(0).(func() domain.UserRepository); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.UserRepository)
		}
	}
	return r0
}

// MockUnitOfWork_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type MockUnitOfWork_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) User() *MockUnitOfWork_User_Call {
	return &MockUnitOfWork_User_Call{Call: _e.mock.On("User")}
}

func (_c *MockUnitOfWork_User_Call) Run(run func()) *MockUnitOfWork_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_User_Call) Return(userRepository domain.UserRepository) *MockUnitOfWork_User_Call {
	_c.Call.Return(userRepository)
	return _c
}

func (_c *MockUnitOfWork_User_Call) RunAndReturn(run func() domain.UserRepository) *MockUnitOfWork_User_Call {
	_c.Call.Return(run)
	return _c
}
