// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIngestionRepository creates a new instance of MockIngestionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestionRepository {
	mock := &MockIngestionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngestionRepository is an autogenerated mock type for the IngestionRepository type
type MockIngestionRepository struct {
	mock.Mock
}

type MockIngestionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestionRepository) EXPECT() *MockIngestionRepository_Expecter {
	return &MockIngestionRepository_Expecter{mock: &_m.Mock}
}

// BatchInsert provides a mock function for the type MockIngestionRepository
func (_mock *MockIngestionRepository) BatchInsert(ctx context.Context, events []*domain.Event) error {
	ret := _mock.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for BatchInsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*domain.Event) error); ok {
		r0 = returnFunc(ctx, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIngestionRepository_BatchInsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchInsert'
type MockIngestionRepository_BatchInsert_Call struct {
	*mock.Call
}

// BatchInsert is a helper method to define mock.On call
//   - ctx context.Context
//   - events []*domain.Event
func (_e *MockIngestionRepository_Expecter) BatchInsert(ctx interface{}, events interface{}) *MockIngestionRepository_BatchInsert_Call {
	return &MockIngestionRepository_BatchInsert_Call{Call: _e.mock.On("BatchInsert", ctx, events)}
}

func (_c *MockIngestionRepository_BatchInsert_Call) Run(run func(ctx context.Context, events []*domain.Event)) *MockIngestionRepository_BatchInsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*domain.Event
		if args[1] != nil {
			arg1 = args[1].([]*domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngestionRepository_BatchInsert_Call) Return(err error) *MockIngestionRepository_BatchInsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIngestionRepository_BatchInsert_Call) RunAndReturn(run func(ctx context.Context, events []*domain.Event) error) *MockIngestionRepository_BatchInsert_Call {
	_c.Call.Return(run)
	return _c
}
