// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryUseCase creates a new instance of MockQueryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryUseCase {
	mock := &MockQueryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryUseCase is an autogenerated mock type for the QueryUseCase type
type MockQueryUseCase struct {
	mock.Mock
}

type MockQueryUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryUseCase) EXPECT() *MockQueryUseCase_Expecter {
	return &MockQueryUseCase_Expecter{mock: &_m.Mock}
}

// SyncQuery provides a mock function for the type MockQueryUseCase
func (_mock *MockQueryUseCase) SyncQuery(ctx context.Context, req *domain.QueryAstRequest) (*domain.QueryResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SyncQuery")
	}

	var r0 *domain.QueryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.QueryAstRequest) (*domain.QueryResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.QueryAstRequest) *domain.QueryResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.QueryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.QueryAstRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryUseCase_SyncQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncQuery'
type MockQueryUseCase_SyncQuery_Call struct {
	*mock.Call
}

// SyncQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.QueryAstRequest
func (_e *MockQueryUseCase_Expecter) SyncQuery(ctx interface{}, req interface{}) *MockQueryUseCase_SyncQuery_Call {
	return &MockQueryUseCase_SyncQuery_Call{Call: _e.mock.On("SyncQuery", ctx, req)}
}

func (_c *MockQueryUseCase_SyncQuery_Call) Run(run func(ctx context.Context, req *domain.QueryAstRequest)) *MockQueryUseCase_SyncQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.QueryAstRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.QueryAstRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueryUseCase_SyncQuery_Call) Return(queryResponse *domain.QueryResponse, err error) *MockQueryUseCase_SyncQuery_Call {
	_c.Call.Return(queryResponse, err)
	return _c
}

func (_c *MockQueryUseCase_SyncQuery_Call) RunAndReturn(run func(ctx context.Context, req *domain.QueryAstRequest) (*domain.QueryResponse, error)) *MockQueryUseCase_SyncQuery_Call {
	_c.Call.Return(run)
	return _c
}
