// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTxContext creates a new instance of MockTxContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTxContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTxContext {
	mock := &MockTxContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTxContext is an autogenerated mock type for the TxContext type
type MockTxContext struct {
	mock.Mock
}

type MockTxContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTxContext) EXPECT() *MockTxContext_Expecter {
	return &MockTxContext_Expecter{mock: &_m.Mock}
}
