// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDriver creates a new instance of MockDriver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDriver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDriver {
	mock := &MockDriver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDriver is an autogenerated mock type for the Driver type
type MockDriver struct {
	mock.Mock
}

type MockDriver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDriver) EXPECT() *MockDriver_Expecter {
	return &MockDriver_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type MockDriver
func (_mock *MockDriver) Begin() (domain.Tx, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 domain.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (domain.Tx, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() domain.Tx); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockDriver_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Begin() *MockDriver_Begin_Call {
	return &MockDriver_Begin_Call{Call: _e.mock.On("Begin")}
}

func (_c *MockDriver_Begin_Call) Run(run func()) *MockDriver_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Begin_Call) Return(tx domain.Tx, err error) *MockDriver_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockDriver_Begin_Call) RunAndReturn(run func() (domain.Tx, error)) *MockDriver_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function for the type MockDriver
func (_mock *MockDriver) BeginTx(ctx context.Context, opts *sql.TxOptions) (domain.Tx, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 domain.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (domain.Tx, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) domain.Tx); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockDriver_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockDriver_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockDriver_BeginTx_Call {
	return &MockDriver_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockDriver_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockDriver_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.TxOptions
		if args[1] != nil {
			arg1 = args[1].(*sql.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDriver_BeginTx_Call) Return(tx domain.Tx, err error) *MockDriver_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockDriver_BeginTx_Call) RunAndReturn(run func(ctx context.Context, opts *sql.TxOptions) (domain.Tx, error)) *MockDriver_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockDriver
func (_mock *MockDriver) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDriver_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDriver_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDriver_Expecter) Close() *MockDriver_Close_Call {
	return &MockDriver_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDriver_Close_Call) Run(run func()) *MockDriver_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDriver_Close_Call) Return(err error) *MockDriver_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDriver_Close_Call) RunAndReturn(run func() error) *MockDriver_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockDriver
func (_mock *MockDriver) Query(query domain.Query, args ...domain.QueryArgs) (*sql.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(query, args)
	} else {
		tmpRet = _mock.Called(query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Query, ...domain.QueryArgs) (*sql.Rows, error)); ok {
		return returnFunc(query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Query, ...domain.QueryArgs) *sql.Rows); ok {
		r0 = returnFunc(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Query, ...domain.QueryArgs) error); ok {
		r1 = returnFunc(query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDriver_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query domain.Query
//   - args ...domain.QueryArgs
func (_e *MockDriver_Expecter) Query(query interface{}, args ...interface{}) *MockDriver_Query_Call {
	return &MockDriver_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *MockDriver_Query_Call) Run(run func(query domain.Query, args ...domain.QueryArgs)) *MockDriver_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Query
		if args[0] != nil {
			arg0 = args[0].(domain.Query)
		}
		var arg1 []domain.QueryArgs
		var variadicArgs []domain.QueryArgs
		if len(args) > 1 {
			variadicArgs = args[1].([]domain.QueryArgs)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockDriver_Query_Call) Return(rows *sql.Rows, err error) *MockDriver_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockDriver_Query_Call) RunAndReturn(run func(query domain.Query, args ...domain.QueryArgs) (*sql.Rows, error)) *MockDriver_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type MockDriver
func (_mock *MockDriver) QueryContext(ctx context.Context, query domain.Query, args ...domain.QueryArgs) (*sql.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, query, args)
	} else {
		tmpRet = _mock.Called(ctx, query)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Query, ...domain.QueryArgs) (*sql.Rows, error)); ok {
		return returnFunc(ctx, query, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Query, ...domain.QueryArgs) *sql.Rows); ok {
		r0 = returnFunc(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Query, ...domain.QueryArgs) error); ok {
		r1 = returnFunc(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDriver_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockDriver_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query domain.Query
//   - args ...domain.QueryArgs
func (_e *MockDriver_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockDriver_QueryContext_Call {
	return &MockDriver_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDriver_QueryContext_Call) Run(run func(ctx context.Context, query domain.Query, args ...domain.QueryArgs)) *MockDriver_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Query
		if args[1] != nil {
			arg1 = args[1].(domain.Query)
		}
		var arg2 []domain.QueryArgs
		var variadicArgs []domain.QueryArgs
		if len(args) > 2 {
			variadicArgs = args[2].([]domain.QueryArgs)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDriver_QueryContext_Call) Return(rows *sql.Rows, err error) *MockDriver_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockDriver_QueryContext_Call) RunAndReturn(run func(ctx context.Context, query domain.Query, args ...domain.QueryArgs) (*sql.Rows, error)) *MockDriver_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}
