// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthStatus creates a new instance of MockHealthStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthStatus {
	mock := &MockHealthStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthStatus is an autogenerated mock type for the HealthStatus type
type MockHealthStatus struct {
	mock.Mock
}

type MockHealthStatus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthStatus) EXPECT() *MockHealthStatus_Expecter {
	return &MockHealthStatus_Expecter{mock: &_m.Mock}
}

// IsHealthy provides a mock function for the type MockHealthStatus
func (_mock *MockHealthStatus) IsHealthy() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockHealthStatus_IsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHealthy'
type MockHealthStatus_IsHealthy_Call struct {
	*mock.Call
}

// IsHealthy is a helper method to define mock.On call
func (_e *MockHealthStatus_Expecter) IsHealthy() *MockHealthStatus_IsHealthy_Call {
	return &MockHealthStatus_IsHealthy_Call{Call: _e.mock.On("IsHealthy")}
}

func (_c *MockHealthStatus_IsHealthy_Call) Run(run func()) *MockHealthStatus_IsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthStatus_IsHealthy_Call) Return(b bool) *MockHealthStatus_IsHealthy_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockHealthStatus_IsHealthy_Call) RunAndReturn(run func() bool) *MockHealthStatus_IsHealthy_Call {
	_c.Call.Return(run)
	return _c
}
