// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizationRepository creates a new instance of MockOrganizationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizationRepository {
	mock := &MockOrganizationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizationRepository is an autogenerated mock type for the OrganizationRepository type
type MockOrganizationRepository struct {
	mock.Mock
}

type MockOrganizationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizationRepository) EXPECT() *MockOrganizationRepository_Expecter {
	return &MockOrganizationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Create(ctx context.Context, org *domain.Organization) error {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Organization) error); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrganizationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - org *domain.Organization
func (_e *MockOrganizationRepository_Expecter) Create(ctx interface{}, org interface{}) *MockOrganizationRepository_Create_Call {
	return &MockOrganizationRepository_Create_Call{Call: _e.mock.On("Create", ctx, org)}
}

func (_c *MockOrganizationRepository_Create_Call) Run(run func(ctx context.Context, org *domain.Organization)) *MockOrganizationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Organization
		if args[1] != nil {
			arg1 = args[1].(*domain.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Create_Call) Return(err error) *MockOrganizationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, org *domain.Organization) error) *MockOrganizationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Delete(ctx context.Context, org *domain.Organization) error {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Organization) error); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOrganizationRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - org *domain.Organization
func (_e *MockOrganizationRepository_Expecter) Delete(ctx interface{}, org interface{}) *MockOrganizationRepository_Delete_Call {
	return &MockOrganizationRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, org)}
}

func (_c *MockOrganizationRepository_Delete_Call) Run(run func(ctx context.Context, org *domain.Organization)) *MockOrganizationRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Organization
		if args[1] != nil {
			arg1 = args[1].(*domain.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Delete_Call) Return(err error) *MockOrganizationRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, org *domain.Organization) error) *MockOrganizationRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) FindAll(ctx context.Context, limit int, offset int) ([]domain.Organization, error) {
	ret := _mock.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Organization, error)); ok {
		return returnFunc(ctx, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []domain.Organization); ok {
		r0 = returnFunc(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockOrganizationRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockOrganizationRepository_Expecter) FindAll(ctx interface{}, limit interface{}, offset interface{}) *MockOrganizationRepository_FindAll_Call {
	return &MockOrganizationRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, limit, offset)}
}

func (_c *MockOrganizationRepository_FindAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockOrganizationRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_FindAll_Call) Return(organizations []domain.Organization, err error) *MockOrganizationRepository_FindAll_Call {
	_c.Call.Return(organizations, err)
	return _c
}

func (_c *MockOrganizationRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int) ([]domain.Organization, error)) *MockOrganizationRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneByID provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) FindOneByID(ctx context.Context, identifier string) (*domain.Organization, error) {
	ret := _mock.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for FindOneByID")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Organization, error)); ok {
		return returnFunc(ctx, identifier)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Organization); ok {
		r0 = returnFunc(ctx, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizationRepository_FindOneByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneByID'
type MockOrganizationRepository_FindOneByID_Call struct {
	*mock.Call
}

// FindOneByID is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *MockOrganizationRepository_Expecter) FindOneByID(ctx interface{}, identifier interface{}) *MockOrganizationRepository_FindOneByID_Call {
	return &MockOrganizationRepository_FindOneByID_Call{Call: _e.mock.On("FindOneByID", ctx, identifier)}
}

func (_c *MockOrganizationRepository_FindOneByID_Call) Run(run func(ctx context.Context, identifier string)) *MockOrganizationRepository_FindOneByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_FindOneByID_Call) Return(organization *domain.Organization, err error) *MockOrganizationRepository_FindOneByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockOrganizationRepository_FindOneByID_Call) RunAndReturn(run func(ctx context.Context, identifier string) (*domain.Organization, error)) *MockOrganizationRepository_FindOneByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrganizationRepository
func (_mock *MockOrganizationRepository) Update(ctx context.Context, org *domain.Organization) error {
	ret := _mock.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Organization) error); ok {
		r0 = returnFunc(ctx, org)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrganizationRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrganizationRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - org *domain.Organization
func (_e *MockOrganizationRepository_Expecter) Update(ctx interface{}, org interface{}) *MockOrganizationRepository_Update_Call {
	return &MockOrganizationRepository_Update_Call{Call: _e.mock.On("Update", ctx, org)}
}

func (_c *MockOrganizationRepository_Update_Call) Run(run func(ctx context.Context, org *domain.Organization)) *MockOrganizationRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Organization
		if args[1] != nil {
			arg1 = args[1].(*domain.Organization)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizationRepository_Update_Call) Return(err error) *MockOrganizationRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrganizationRepository_Update_Call) RunAndReturn(run func(ctx context.Context, org *domain.Organization) error) *MockOrganizationRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
