// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStmt creates a new instance of MockStmt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStmt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStmt {
	mock := &MockStmt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStmt is an autogenerated mock type for the Stmt type
type MockStmt struct {
	mock.Mock
}

type MockStmt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStmt) EXPECT() *MockStmt_Expecter {
	return &MockStmt_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStmt
func (_mock *MockStmt) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStmt_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStmt_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStmt_Expecter) Close() *MockStmt_Close_Call {
	return &MockStmt_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStmt_Close_Call) Run(run func()) *MockStmt_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStmt_Close_Call) Return(err error) *MockStmt_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStmt_Close_Call) RunAndReturn(run func() error) *MockStmt_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function for the type MockStmt
func (_mock *MockStmt) ExecContext(ctx context.Context, args ...interface{}) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, args)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...interface{}) error); ok {
		r0 = returnFunc(ctx, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStmt_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockStmt_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...interface{}
func (_e *MockStmt_Expecter) ExecContext(ctx interface{}, args ...interface{}) *MockStmt_ExecContext_Call {
	return &MockStmt_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockStmt_ExecContext_Call) Run(run func(ctx context.Context, args ...interface{})) *MockStmt_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockStmt_ExecContext_Call) Return(err error) *MockStmt_ExecContext_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStmt_ExecContext_Call) RunAndReturn(run func(ctx context.Context, args ...interface{}) error) *MockStmt_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}
