// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIngestionUseCase creates a new instance of MockIngestionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngestionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngestionUseCase {
	mock := &MockIngestionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIngestionUseCase is an autogenerated mock type for the IngestionUseCase type
type MockIngestionUseCase struct {
	mock.Mock
}

type MockIngestionUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngestionUseCase) EXPECT() *MockIngestionUseCase_Expecter {
	return &MockIngestionUseCase_Expecter{mock: &_m.Mock}
}

// IngestBatch provides a mock function for the type MockIngestionUseCase
func (_mock *MockIngestionUseCase) IngestBatch(ctx context.Context, request *domain.BatchIngestionRequest) (*domain.BatchIngestionResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for IngestBatch")
	}

	var r0 *domain.BatchIngestionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BatchIngestionRequest) (*domain.BatchIngestionResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.BatchIngestionRequest) *domain.BatchIngestionResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BatchIngestionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.BatchIngestionRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIngestionUseCase_IngestBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IngestBatch'
type MockIngestionUseCase_IngestBatch_Call struct {
	*mock.Call
}

// IngestBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - request *domain.BatchIngestionRequest
func (_e *MockIngestionUseCase_Expecter) IngestBatch(ctx interface{}, request interface{}) *MockIngestionUseCase_IngestBatch_Call {
	return &MockIngestionUseCase_IngestBatch_Call{Call: _e.mock.On("IngestBatch", ctx, request)}
}

func (_c *MockIngestionUseCase_IngestBatch_Call) Run(run func(ctx context.Context, request *domain.BatchIngestionRequest)) *MockIngestionUseCase_IngestBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.BatchIngestionRequest
		if args[1] != nil {
			arg1 = args[1].(*domain.BatchIngestionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIngestionUseCase_IngestBatch_Call) Return(batchIngestionResponse *domain.BatchIngestionResponse, err error) *MockIngestionUseCase_IngestBatch_Call {
	_c.Call.Return(batchIngestionResponse, err)
	return _c
}

func (_c *MockIngestionUseCase_IngestBatch_Call) RunAndReturn(run func(ctx context.Context, request *domain.BatchIngestionRequest) (*domain.BatchIngestionResponse, error)) *MockIngestionUseCase_IngestBatch_Call {
	_c.Call.Return(run)
	return _c
}
