// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMembershipRepository creates a new instance of MockMembershipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMembershipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMembershipRepository {
	mock := &MockMembershipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMembershipRepository is an autogenerated mock type for the MembershipRepository type
type MockMembershipRepository struct {
	mock.Mock
}

type MockMembershipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMembershipRepository) EXPECT() *MockMembershipRepository_Expecter {
	return &MockMembershipRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMembershipRepository
func (_mock *MockMembershipRepository) Create(ctx context.Context, membership *domain.Membership) error {
	ret := _mock.Called(ctx, membership)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Membership) error); ok {
		r0 = returnFunc(ctx, membership)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMembershipRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMembershipRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - membership *domain.Membership
func (_e *MockMembershipRepository_Expecter) Create(ctx interface{}, membership interface{}) *MockMembershipRepository_Create_Call {
	return &MockMembershipRepository_Create_Call{Call: _e.mock.On("Create", ctx, membership)}
}

func (_c *MockMembershipRepository_Create_Call) Run(run func(ctx context.Context, membership *domain.Membership)) *MockMembershipRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Membership
		if args[1] != nil {
			arg1 = args[1].(*domain.Membership)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMembershipRepository_Create_Call) Return(err error) *MockMembershipRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMembershipRepository_Create_Call) RunAndReturn(run func(ctx context.Context, membership *domain.Membership) error) *MockMembershipRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockMembershipRepository
func (_mock *MockMembershipRepository) WithTx(tx interface{}) domain.MembershipRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 domain.MembershipRepository
	if returnFunc, ok := ret.Get(0).(func(interface{}) domain.MembershipRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.MembershipRepository)
		}
	}
	return r0
}

// MockMembershipRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockMembershipRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx interface{}
func (_e *MockMembershipRepository_Expecter) WithTx(tx interface{}) *MockMembershipRepository_WithTx_Call {
	return &MockMembershipRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockMembershipRepository_WithTx_Call) Run(run func(tx interface{})) *MockMembershipRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMembershipRepository_WithTx_Call) Return(membershipRepository domain.MembershipRepository) *MockMembershipRepository_WithTx_Call {
	_c.Call.Return(membershipRepository)
	return _c
}

func (_c *MockMembershipRepository_WithTx_Call) RunAndReturn(run func(tx interface{}) domain.MembershipRepository) *MockMembershipRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
