// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/hoppermq/streamly/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetOrganizationByID provides a mock function for the type MockClient
func (_mock *MockClient) GetOrganizationByID(ctx context.Context, organizationId uuid.UUID) (*domain.Organization, error) {
	ret := _mock.Called(ctx, organizationId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizationByID")
	}

	var r0 *domain.Organization
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Organization, error)); ok {
		return returnFunc(ctx, organizationId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Organization); ok {
		r0 = returnFunc(ctx, organizationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organization)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, organizationId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetOrganizationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganizationByID'
type MockClient_GetOrganizationByID_Call struct {
	*mock.Call
}

// GetOrganizationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationId uuid.UUID
func (_e *MockClient_Expecter) GetOrganizationByID(ctx interface{}, organizationId interface{}) *MockClient_GetOrganizationByID_Call {
	return &MockClient_GetOrganizationByID_Call{Call: _e.mock.On("GetOrganizationByID", ctx, organizationId)}
}

func (_c *MockClient_GetOrganizationByID_Call) Run(run func(ctx context.Context, organizationId uuid.UUID)) *MockClient_GetOrganizationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetOrganizationByID_Call) Return(organization *domain.Organization, err error) *MockClient_GetOrganizationByID_Call {
	_c.Call.Return(organization, err)
	return _c
}

func (_c *MockClient_GetOrganizationByID_Call) RunAndReturn(run func(ctx context.Context, organizationId uuid.UUID) (*domain.Organization, error)) *MockClient_GetOrganizationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockClient
func (_mock *MockClient) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockClient_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockClient_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockClient_GetUserByEmail_Call {
	return &MockClient_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockClient_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockClient_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetUserByEmail_Call) Return(user *domain.User, err error) *MockClient_GetUserByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockClient_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockClient
func (_mock *MockClient) GetUserByID(ctx context.Context, userId string) (*domain.User, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockClient_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockClient_Expecter) GetUserByID(ctx interface{}, userId interface{}) *MockClient_GetUserByID_Call {
	return &MockClient_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userId)}
}

func (_c *MockClient_GetUserByID_Call) Run(run func(ctx context.Context, userId string)) *MockClient_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetUserByID_Call) Return(user *domain.User, err error) *MockClient_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userId string) (*domain.User, error)) *MockClient_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUserName provides a mock function for the type MockClient
func (_mock *MockClient) GetUserByUserName(ctx context.Context, userName string) (*domain.User, error) {
	ret := _mock.Called(ctx, userName)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUserName")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, userName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, userName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUserByUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUserName'
type MockClient_GetUserByUserName_Call struct {
	*mock.Call
}

// GetUserByUserName is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
func (_e *MockClient_Expecter) GetUserByUserName(ctx interface{}, userName interface{}) *MockClient_GetUserByUserName_Call {
	return &MockClient_GetUserByUserName_Call{Call: _e.mock.On("GetUserByUserName", ctx, userName)}
}

func (_c *MockClient_GetUserByUserName_Call) Run(run func(ctx context.Context, userName string)) *MockClient_GetUserByUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetUserByUserName_Call) Return(user *domain.User, err error) *MockClient_GetUserByUserName_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockClient_GetUserByUserName_Call) RunAndReturn(run func(ctx context.Context, userName string) (*domain.User, error)) *MockClient_GetUserByUserName_Call {
	_c.Call.Return(run)
	return _c
}
